application: {{your app name}}
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /statics
  static_dir: statics

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest

inbound_services:
- channel_presence
